export default {
  LOGIN: 'LOGIN',
  FORGET_PASSWORD: 'FORGET_PASSWORD',
  HOME_DATA:"HOME_DATA",
  HOME_LOADING:"HOME_LOADING",
  HOME_LOADING_OFF:"HOME_LOADING_OFF",
  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  APP_DATA: 'APP_DATA',
  NO_INTERNET: "NO_INTERNET",
};
